"""Add ot_override_amount to Payroll

Revision ID: 3265f5ffd20a
Revises: 953b7c27b680
Create Date: 2026-01-11 21:05:20.012016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3265f5ffd20a'
down_revision = '953b7c27b680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hrm_ot_daily_summary', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_ot_daily_emp_date', ['employee_id', 'ot_date'])

    with op.batch_alter_table('hrm_payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ot_override_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hrm_payroll', schema=None) as batch_op:
        batch_op.drop_column('ot_override_amount')

    with op.batch_alter_table('hrm_ot_daily_summary', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ot_daily_emp_date', type_='unique')

    # ### end Alembic commands ###
