"""Add Email Service tables

Revision ID: 66f746e7b384
Revises: add_header_image_payslip
Create Date: 2026-01-26 18:23:28.835769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f746e7b384'
down_revision = 'add_header_image_payslip'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hrm_email_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_user', sa.String(length=255), nullable=False),
    sa.Column('smtp_password', sa.String(length=255), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('use_ssl', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['hrm_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    with op.batch_alter_table('hrm_email_config', schema=None) as batch_op:
        batch_op.create_index('idx_hrm_email_config_tenant_id', ['tenant_id'], unique=False)

    op.create_table('hrm_email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['hrm_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hrm_email_log', schema=None) as batch_op:
        batch_op.create_index('idx_hrm_email_log_sent_at', ['sent_at'], unique=False)
        batch_op.create_index('idx_hrm_email_log_tenant_id', ['tenant_id'], unique=False)

    op.create_table('hrm_report_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['hrm_users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['hrm_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hrm_report_schedule', schema=None) as batch_op:
        batch_op.create_index('idx_hrm_report_schedule_tenant_id', ['tenant_id'], unique=False)

    # with op.batch_alter_table('hrm_ot_daily_summary', schema=None) as batch_op:
    #     batch_op.create_unique_constraint('uq_ot_daily_emp_date', ['employee_id', 'ot_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('hrm_ot_daily_summary', schema=None) as batch_op:
    #     batch_op.drop_constraint('uq_ot_daily_emp_date', type_='unique')

    with op.batch_alter_table('hrm_report_schedule', schema=None) as batch_op:
        batch_op.drop_index('idx_hrm_report_schedule_tenant_id')

    op.drop_table('hrm_report_schedule')
    with op.batch_alter_table('hrm_email_log', schema=None) as batch_op:
        batch_op.drop_index('idx_hrm_email_log_tenant_id')
        batch_op.drop_index('idx_hrm_email_log_sent_at')

    op.drop_table('hrm_email_log')
    with op.batch_alter_table('hrm_email_config', schema=None) as batch_op:
        batch_op.drop_index('idx_hrm_email_config_tenant_id')

    op.drop_table('hrm_email_config')
    # ### end Alembic commands ###
