"""Attendance Status and Regularization

Revision ID: 776f81c4fa9c
Revises: fd2753788eba
Create Date: 2025-12-30 14:53:58.044023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '776f81c4fa9c'
down_revision = 'fd2753788eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hrm_attendance_regularization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('original_clock_in', sa.DateTime(), nullable=True),
    sa.Column('original_clock_out', sa.DateTime(), nullable=True),
    sa.Column('corrected_clock_in', sa.DateTime(), nullable=False),
    sa.Column('corrected_clock_out', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('proof_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['hrm_users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['hrm_employee.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['hrm_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Check if hrm_roles exists and drop it if it does (to allow rename)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'hrm_roles' in inspector.get_table_names():
        op.drop_table('hrm_roles')
    op.rename_table('role', 'hrm_roles')
    
    # Create Enum type if not exists
    attendance_status_enum = sa.Enum('Present', 'Incomplete', 'Absent', 'Leave', name='attendance_status_enum')
    attendance_status_enum.create(op.get_bind(), checkfirst=True)

    # Migrate existing status values
    op.execute("UPDATE hrm_attendance SET status = 'Present' WHERE status IN ('Late', 'Half Day')")
    op.execute("UPDATE hrm_attendance SET status = 'Leave' WHERE status IN ('On Leave', 'Holiday')")
    op.execute("UPDATE hrm_attendance SET status = 'Incomplete' WHERE status = 'Pending'")
    # Safety fallback
    op.execute("UPDATE hrm_attendance SET status = 'Incomplete' WHERE status NOT IN ('Present', 'Absent', 'Leave', 'Incomplete')")

    with op.batch_alter_table('hrm_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clock_in_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('clock_out_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sub_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('leave_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('regularization_id', sa.Integer(), nullable=True))
        batch_op.alter_column('has_overtime',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Present', 'Incomplete', 'Absent', 'Leave', name='attendance_status_enum'),
               existing_nullable=True,
               postgresql_using='status::attendance_status_enum')
        batch_op.drop_index(batch_op.f('ix_hrm_attendance_has_overtime'))
        batch_op.create_foreign_key(None, 'hrm_leave', ['leave_id'], ['id'])
        batch_op.create_foreign_key(None, 'hrm_attendance_regularization', ['regularization_id'], ['id'])
        
    # Set default values for existing nulls in hrm_company
    op.execute("UPDATE hrm_company SET currency_code = 'SGD' WHERE currency_code IS NULL")
    op.execute("UPDATE hrm_company SET timezone = 'UTC' WHERE timezone IS NULL")

    with op.batch_alter_table('hrm_company', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Foreign key to hrm_tenant',
               existing_nullable=False)
        batch_op.alter_column('uen',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Singapore Unique Entity Number',
               existing_nullable=True)
        batch_op.alter_column('currency_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('modified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_table_comment(
        existing_comment='Company entities belonging to a tenant'
    )

    with op.batch_alter_table('hrm_employee', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('nric',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_hrm_employee_company_id'))
        batch_op.drop_index(batch_op.f('idx_nric_unique_partial'), postgresql_where='(nric IS NOT NULL)')
        batch_op.drop_index(batch_op.f('ix_hrm_employee_overtime_group_id'))
        batch_op.create_foreign_key(None, 'hrm_designation', ['designation_id'], ['id'])
        batch_op.create_foreign_key(None, 'hrm_employee_group', ['employee_group_id'], ['id'])

    with op.batch_alter_table('hrm_employee_documents', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('hrm_leave_type', schema=None) as batch_op:
        batch_op.alter_column('annual_allocation',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'#3498db'::character varying"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('hrm_ot_type', schema=None) as batch_op:
        batch_op.drop_column('applicable_days')

    with op.batch_alter_table('hrm_tenant', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Unique tenant code for identification',
               existing_nullable=False)
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Country code (e.g., SG, US, IN)',
               existing_nullable=True)
        batch_op.alter_column('currency_code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Currency code (e.g., SGD, USD, INR)',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('modified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_table_comment(
        existing_comment='Top-level tenant entity for multi-tenant HRMS'
    )

    with op.batch_alter_table('hrm_tenant_documents', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Relative path under static/uploads/',
               existing_nullable=False)
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Document type: Contract, Agreement, License, etc.',
               existing_nullable=True)
        batch_op.alter_column('upload_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_table_comment(
        existing_comment='Tenant document attachments'
    )

    with op.batch_alter_table('hrm_tenant_payment_config', schema=None) as batch_op:
        batch_op.alter_column('payment_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Payment type: Fixed or User-Based',
               existing_nullable=False,
               existing_server_default=sa.text("'Fixed'::character varying"))
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Payment collection frequency',
               existing_nullable=False,
               existing_server_default=sa.text("'Monthly'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('modified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_table_comment(
        existing_comment='Tenant payment configuration for billing management'
    )

    with op.batch_alter_table('hrm_user_role_mapping', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('hrm_user_role_mapping_role_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'hrm_roles', ['role_id'], ['id'], ondelete='CASCADE')

    # Set default values for existing nulls in hrm_users
    op.execute("UPDATE hrm_users SET email = 'no_email_' || id || '@example.com' WHERE email IS NULL")
    # Set default organization if null (using first available organization)
    op.execute("UPDATE hrm_users SET organization_id = (SELECT id FROM organization LIMIT 1) WHERE organization_id IS NULL")

    with op.batch_alter_table('hrm_users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('hrm_users_role_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('hrm_users_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'hrm_roles', ['role_id'], ['id'])
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_organization_tenant_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_organization_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('hrm_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('hrm_users_tenant_id_fkey'), 'hrm_tenant', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('hrm_users_role_id_fkey'), 'role', ['role_id'], ['id'])
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('hrm_user_role_mapping', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('hrm_user_role_mapping_role_id_fkey'), 'role', ['role_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('hrm_tenant_payment_config', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Tenant payment configuration for billing management',
        existing_comment=None
    )
        batch_op.alter_column('modified_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=20),
               comment='Payment collection frequency',
               existing_nullable=False,
               existing_server_default=sa.text("'Monthly'::character varying"))
        batch_op.alter_column('payment_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Payment type: Fixed or User-Based',
               existing_nullable=False,
               existing_server_default=sa.text("'Fixed'::character varying"))

    with op.batch_alter_table('hrm_tenant_documents', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Tenant document attachments',
        existing_comment=None
    )
        batch_op.alter_column('upload_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Document type: Contract, Agreement, License, etc.',
               existing_nullable=True)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               comment='Relative path under static/uploads/',
               existing_nullable=False)

    with op.batch_alter_table('hrm_tenant', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Top-level tenant entity for multi-tenant HRMS',
        existing_comment=None
    )
        batch_op.alter_column('modified_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('currency_code',
               existing_type=sa.VARCHAR(length=10),
               comment='Currency code (e.g., SGD, USD, INR)',
               existing_nullable=True)
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(length=10),
               comment='Country code (e.g., SG, US, IN)',
               existing_nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique tenant code for identification',
               existing_nullable=False)

    with op.batch_alter_table('hrm_ot_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applicable_days', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('hrm_leave_type', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'#3498db'::character varying"))
        batch_op.alter_column('annual_allocation',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('hrm_employee_documents', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('hrm_employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_hrm_employee_overtime_group_id'), ['overtime_group_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_nric_unique_partial'), ['nric'], unique=True, postgresql_where='(nric IS NOT NULL)')
        batch_op.create_index(batch_op.f('idx_hrm_employee_company_id'), ['company_id'], unique=False)
        batch_op.alter_column('nric',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('hrm_company', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Company entities belonging to a tenant',
        existing_comment=None
    )
        batch_op.alter_column('modified_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('timezone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('currency_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('uen',
               existing_type=sa.VARCHAR(length=50),
               comment='Singapore Unique Entity Number',
               existing_nullable=True)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               comment='Foreign key to hrm_tenant',
               existing_nullable=False)

    with op.batch_alter_table('hrm_attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_hrm_attendance_has_overtime'), ['has_overtime'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('Present', 'Incomplete', 'Absent', 'Leave', name='attendance_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('has_overtime',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_column('regularization_id')
        batch_op.drop_column('leave_id')
        batch_op.drop_column('sub_status')
        batch_op.drop_column('clock_out_time')
        batch_op.drop_column('clock_in_time')

    op.rename_table('hrm_roles', 'role')
    op.drop_table('hrm_attendance_regularization')
    
    # Drop Enum type
    sa.Enum(name='attendance_status_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
