"""Add other_deductions and remarks to Payroll

Revision ID: 7c5d97703251
Revises: 66f746e7b384
Create Date: 2026-01-28 23:02:24.499461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5d97703251'
down_revision = '66f746e7b384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hrm_ot_daily_summary', schema=None) as batch_op:
        pass # batch_op.create_unique_constraint('uq_ot_daily_emp_date', ['employee_id', 'ot_date'])

    with op.batch_alter_table('hrm_payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hrm_payroll', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    with op.batch_alter_table('hrm_ot_daily_summary', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ot_daily_emp_date', type_='unique')

    # ### end Alembic commands ###
