"""Add basic_salary to PayrollConfiguration

Revision ID: 953b7c27b680
Revises: add_payslip_logos
Create Date: 2026-01-10 21:30:59.810023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953b7c27b680'
down_revision = 'add_payslip_logos'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hrm_holiday', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['date', 'company_id'])

    with op.batch_alter_table('hrm_payroll_configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basic_salary', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hrm_payroll_configuration', schema=None) as batch_op:
        batch_op.drop_column('basic_salary')

    with op.batch_alter_table('hrm_holiday', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
