"""professional_invoice_enhancements

Revision ID: 9e27b5a662d2
Revises: 2cd06a815ffc
Create Date: 2026-03-06 02:26:58.737235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e27b5a662d2'
down_revision = '2cd06a815ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hrm_invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['hrm_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hrm_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('billing_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes_terms', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('hrm_invoices', schema=None) as batch_op:
        batch_op.drop_column('notes_terms')
        batch_op.drop_column('billing_address')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('tax_rate')
        batch_op.drop_column('subtotal')

    op.drop_table('hrm_invoice_items')
    # ### end Alembic commands ###
