"""add certification file fields

Revision ID: a1b2c3d4e5f6
Revises: f02b3138dd58
Create Date: 2026-01-14 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'f02b3138dd58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hrm_employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hazmat_file_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('airport_pass_file_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('psa_pass_file_id', sa.Integer(), nullable=True))
        
        batch_op.create_foreign_key(None, 'hrm_file_storage', ['hazmat_file_id'], ['id'])
        batch_op.create_foreign_key(None, 'hrm_file_storage', ['airport_pass_file_id'], ['id'])
        batch_op.create_foreign_key(None, 'hrm_file_storage', ['psa_pass_file_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hrm_employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        
        batch_op.drop_column('psa_pass_file_id')
        batch_op.drop_column('airport_pass_file_id')
        batch_op.drop_column('hazmat_file_id')

    # ### end Alembic commands ###
