"""add header image to payslip templates

Revision ID: add_header_image_payslip
Revises: 
Create Date: 2026-01-17 10:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_header_image_payslip'
down_revision = ('f02b3138dd58', 'b2c3d4e5f6g7')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.add_column('hrm_payslip_templates', sa.Column('header_image_path', sa.String(length=255), nullable=True))
    op.add_column('hrm_payslip_templates', sa.Column('header_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_payslip_template_header_img', 'hrm_payslip_templates', 'hrm_file_storage', ['header_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_constraint('fk_payslip_template_header_img', 'hrm_payslip_templates', type_='foreignkey')
    op.drop_column('hrm_payslip_templates', 'header_image_id')
    op.drop_column('hrm_payslip_templates', 'header_image_path')
    # ### end Alembic commands ###
