"""Add attendance segments and late/early flags

Revision ID: c2d2f9ba8d12
Revises: 7eebafa5e2e0
Create Date: 2026-01-02 18:06:16.351585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d2f9ba8d12'
down_revision = '7eebafa5e2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hrm_attendance_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('segment_type', sa.String(length=20), nullable=True),
    sa.Column('clock_in', sa.DateTime(), nullable=False),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('location_lat', sa.String(length=20), nullable=True),
    sa.Column('location_lng', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['hrm_attendance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hrm_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_late', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_early_departure', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('late_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('early_departure_minutes', sa.Integer(), nullable=True))

    with op.batch_alter_table('hrm_roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('hrm_working_hours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grace_period', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hrm_working_hours', schema=None) as batch_op:
        batch_op.drop_column('grace_period')

    with op.batch_alter_table('hrm_roles', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('hrm_attendance', schema=None) as batch_op:
        batch_op.drop_column('early_departure_minutes')
        batch_op.drop_column('late_minutes')
        batch_op.drop_column('is_early_departure')
        batch_op.drop_column('is_late')

    op.drop_table('hrm_attendance_segments')
    # ### end Alembic commands ###
