"""add profile_picture_id and filestorage fks

Revision ID: f02b3138dd58
Revises: 3265f5ffd20a
Create Date: 2026-01-14 09:36:04.983202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02b3138dd58'
down_revision = '3265f5ffd20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hrm_attendance_regularization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_file_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hrm_file_storage', ['proof_file_id'], ['id'])

    with op.batch_alter_table('hrm_employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hrm_file_storage', ['profile_picture_id'], ['id'])

    with op.batch_alter_table('hrm_employee_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_storage_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hrm_file_storage', ['file_storage_id'], ['id'])

    with op.batch_alter_table('hrm_ot_daily_summary', schema=None) as batch_op:
        # batch_op.create_unique_constraint('uq_ot_daily_emp_date', ['employee_id', 'ot_date'])
        pass

    with op.batch_alter_table('hrm_payslip_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('left_logo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('right_logo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('watermark_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('footer_image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hrm_file_storage', ['footer_image_id'], ['id'])
        batch_op.create_foreign_key(None, 'hrm_file_storage', ['right_logo_id'], ['id'])
        batch_op.create_foreign_key(None, 'hrm_file_storage', ['logo_id'], ['id'])
        batch_op.create_foreign_key(None, 'hrm_file_storage', ['left_logo_id'], ['id'])
        batch_op.create_foreign_key(None, 'hrm_file_storage', ['watermark_id'], ['id'])

    with op.batch_alter_table('hrm_tenant_configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payslip_logo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hrm_file_storage', ['payslip_logo_id'], ['id'])

    with op.batch_alter_table('hrm_tenant_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_storage_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hrm_file_storage', ['file_storage_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hrm_tenant_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('file_storage_id')

    with op.batch_alter_table('hrm_tenant_configuration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payslip_logo_id')

    with op.batch_alter_table('hrm_payslip_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('footer_image_id')
        batch_op.drop_column('watermark_id')
        batch_op.drop_column('right_logo_id')
        batch_op.drop_column('left_logo_id')
        batch_op.drop_column('logo_id')

    with op.batch_alter_table('hrm_ot_daily_summary', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ot_daily_emp_date', type_='unique')

    with op.batch_alter_table('hrm_employee_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('file_storage_id')

    with op.batch_alter_table('hrm_employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('profile_picture_id')

    with op.batch_alter_table('hrm_attendance_regularization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proof_file_id')

    # ### end Alembic commands ###
