name: Daily Attendance Auto-Creation

on:
  schedule:
    # Run daily at 12:01 AM UTC (adjust timezone as needed)
    - cron: '1 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  create-attendance:
    runs-on: ubuntu-latest
    
    steps:
    - name: Create Daily Attendance Records
      run: |
        curl -X POST "${{ secrets.APP_URL }}/api/attendance/auto-create" \
          -H "X-API-Key: ${{ secrets.ATTENDANCE_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"date": "'$(date +%Y-%m-%d)'"}'
      
    - name: Notify on failure
      if: failure()
      run: |
        echo "Daily attendance creation failed!"
        # You can add notification logic here (Slack, email, etc.)